Add RTL support
TakuSemba/MultiSnapRecyclerView pull request #19
Opened 2019-03-18 19:36 UTC by DenysZP

This PR adds support for right-to-left (RTL) layout direction.

2020-10-25 08:57 UTC, buornhnufnofnr requested changes

2020-10-25 08:57 UTC, buornhnufnofnr commented on multisnaprecyclerview/src/main/java/com/takusemba/multisnaprecyclerview/MultiSnapRecyclerView.java
> +    final boolean isRtl;
(gravity, snapCount, new LinearSmoothScroller(context) {

2020-10-25 08:58 UTC, buornhnufnofnr approved these changes

2020-10-26 05:52 UTC, TakuSemba commented
Hi, Thank you for the PR.

Though I appreciate you created the PR, I'm closing this because the codebase was already migrated into Kotlin and the conflict is too huge to look at.

I would be really happy if you could apply the changes to the current Kotlin codebase.

2020-10-26 05:52 UTC, closed without merging